language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8

    - PROJECT="Weather Alert.xcodeproj"
    - IOS_SCHEME="Weather Alert"
    - IOS_SDK=iphonesimulator10.0

  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME"

script:
  - xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
